# In this directory, run the following command to build this builder.
# $ gcloud container builds submit . --config=cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/npm-ssh', '.']


# Print npm version.
- name: 'gcr.io/$PROJECT_ID/npm-ssh'
  args: ['version']

# Test the examples.

# hello_world
- name: 'gcr.io/$PROJECT_ID/npm-ssh'
  args: ['install']
  dir: 'examples/hello_world'
- name: 'gcr.io/$PROJECT_ID/npm-ssh'
  args: ['test']
  dir: 'examples/hello_world'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.']
  dir: 'examples/hello_world'

images: ['gcr.io/$PROJECT_ID/npm-ssh']
