steps:
- name: 'gcr.io/$PROJECT_ID/npm-ssh'
  args: ['install']
- name: 'gcr.io/$PROJECT_ID/npm-ssh'
  args: ['test']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/hello_npm', '.']
images: ['gcr.io/$PROJECT_ID/hello_npm']
